# Streamlit Data Contract Verification

## Product & Growth Intelligence Platform

This notebook verifies the structure of the core output datasets that will power the Streamlit application.

For each dataset, we inspect:

- File availability
- Dataset shape
- Column names
- Data types
- Sample records

This verification step ensures that the Streamlit application uses the exact exported data structure from the completed analytics notebooks.

In [1]:
from pathlib import Path
import pandas as pd

# Project paths
PROJECT_ROOT = Path.cwd().parent
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

print("Project root:", PROJECT_ROOT)
print("Outputs directory:", OUTPUTS_DIR)
print("Outputs directory exists:", OUTPUTS_DIR.exists())

Project root: D:\Data science portfolio\03_Product_Growth_Intelligence
Outputs directory: D:\Data science portfolio\03_Product_Growth_Intelligence\outputs
Outputs directory exists: True

In [2]:
CORE_FILES = [
    "06_segment_profile.csv",
    "06_segment_funnel.csv",
    "06_segment_retention.csv",
    "07_product_intelligence.csv",
    "07_category_intelligence.csv",
    "07_product_opportunities.csv",
    "growth_opportunity_engine_output.csv"
]

print("CORE STREAMLIT DATASETS")
print("=" * 70)

for file_name in CORE_FILES:
    file_path = OUTPUTS_DIR / file_name
    status = "FOUND" if file_path.exists() else "MISSING"
    print(f"{status:8} | {file_name}")

CORE STREAMLIT DATASETS
======================================================================
FOUND    | 06_segment_profile.csv
FOUND    | 06_segment_funnel.csv
FOUND    | 06_segment_retention.csv
FOUND    | 07_product_intelligence.csv
FOUND    | 07_category_intelligence.csv
FOUND    | 07_product_opportunities.csv
FOUND    | growth_opportunity_engine_output.csv

In [3]:
verification_results = {}

for file_name in CORE_FILES:
    
    file_path = OUTPUTS_DIR / file_name
    df = pd.read_csv(file_path)
    
    verification_results[file_name] = {
        "shape": df.shape,
        "columns": df.columns.tolist(),
        "dtypes": df.dtypes.astype(str).to_dict(),
        "preview": df.head(3)
    }
    
    print("\n" + "=" * 90)
    print(f"FILE: {file_name}")
    print("=" * 90)
    
    print(f"\nShape: {df.shape}")
    
    print("\nColumns:")
    for i, column in enumerate(df.columns, start=1):
        print(f"{i}. {column}")
    
    print("\nData Types:")
    print(df.dtypes)
    
    print("\nFirst 3 Rows:")
    display(df.head(3))

==========================================================================================
FILE: 06_segment_profile.csv
==========================================================================================

Shape: (8, 12)

Columns:
1. segment
2. visitors
3. avg_active_days
4. median_active_days
5. avg_events
6. avg_views
7. avg_carts
8. avg_transactions
9. avg_unique_products_viewed
10. avg_recency_days
11. buyer_rate_pct
12. returning_rate_pct

Data Types:
segment                        object
visitors                        int64
avg_active_days               float64
median_active_days            float64
avg_events                    float64
avg_views                     float64
avg_carts                     float64
avg_transactions              float64
avg_unique_products_viewed    float64
avg_recency_days              float64
buyer_rate_pct                float64
returning_rate_pct            float64
dtype: object

First 3 Rows:

,segment,visitors,avg_active_days,median_active_days,avg_events,avg_views,avg_carts,avg_transactions,avg_unique_products_viewed,avg_recency_days,buyer_rate_pct,returning_rate_pct
0,Repeat Buyers,1063,6.224835,3.0,116.716839,96.791157,11.268109,8.657573,62.376294,59.736595,100.0,75.729069
1,One-Time Buyers,10656,1.949418,1.0,10.004505,7.307151,1.453547,1.243806,3.964621,65.762481,100.0,39.649024
2,High-Intent Visitors,5823,2.121587,1.0,14.181522,10.653787,3.527735,0.000000,6.488580,62.381762,0.0,40.735016

==========================================================================================
FILE: 06_segment_funnel.csv
==========================================================================================

Shape: (8, 8)

Columns:
1. segment
2. visitors
3. viewed_visitors
4. cart_visitors
5. transaction_visitors
6. view_participation_pct
7. cart_participation_pct
8. transaction_participation_pct

Data Types:
segment                           object
visitors                           int64
viewed_visitors                    int64
cart_visitors                      int64
transaction_visitors               int64
view_participation_pct           float64
cart_participation_pct           float64
transaction_participation_pct    float64
dtype: object

First 3 Rows:

,segment,visitors,viewed_visitors,cart_visitors,transaction_visitors,view_participation_pct,cart_participation_pct,transaction_participation_pct
0,Repeat Buyers,1063,1048,1033,1063,98.588899,97.177799,100.0
1,One-Time Buyers,10656,10243,9543,10656,96.124249,89.555180,100.0
2,High-Intent Visitors,5823,5387,5823,0,92.512451,100.000000,0.0

==========================================================================================
FILE: 06_segment_retention.csv
==========================================================================================

Shape: (8, 4)

Columns:
1. segment
2. D1_retention_pct
3. D7_retention_pct
4. D30_retention_pct

Data Types:
segment               object
D1_retention_pct     float64
D7_retention_pct     float64
D30_retention_pct    float64
dtype: object

First 3 Rows:

                segment  D1_retention_pct  D7_retention_pct  D30_retention_pct
0         Repeat Buyers         35.465663         13.039310           5.732484
1       One-Time Buyers         15.853201          3.247567           0.769840
2  High-Intent Visitors         15.189003          3.644444           1.102162

==========================================================================================
FILE: 07_product_intelligence.csv
==========================================================================================

Shape: (235061, 16)

Columns:
1. itemid
2. visitors
3. view_events
4. cart_events
5. transaction_events
6. viewed_visitors
7. cart_visitors
8. transaction_visitors
9. view_to_cart_pct
10. cart_to_transaction_pct
11. view_to_transaction_pct
12. categoryid
13. view_participation_pct
14. cart_participation_pct
15. transaction_participation_pct
16. root_categoryid

Data Types:
itemid                             int64
visitors                           int64
view_events                        int64
cart_events                        int64
transaction_events                 int64
viewed_visitors                  float64
cart_visitors                    float64
transaction_visitors             float64
view_to_cart_pct                 float64
cart_to_transaction_pct          float64
view_to_transaction_pct          float64
categoryid                       float64
view_participation_pct           float64
cart_participation_pct           float64
transaction_participation_pct    float64
root_categoryid                  float64
dtype: object

First 3 Rows:

,itemid,visitors,view_events,cart_events,transaction_events,viewed_visitors,cart_visitors,transaction_visitors,view_to_cart_pct,cart_to_transaction_pct,view_to_transaction_pct,categoryid,view_participation_pct,cart_participation_pct,transaction_participation_pct,root_categoryid
0,3,2,2,0,0,2.0,0.0,0.0,0.0,NaN,0.0,1171.0,100.0,0.0,0.0,1532.0
1,4,3,3,0,0,3.0,0.0,0.0,0.0,NaN,0.0,1038.0,100.0,0.0,0.0,1532.0
2,6,26,29,0,0,26.0,0.0,0.0,0.0,NaN,0.0,1091.0,100.0,0.0,0.0,1600.0

==========================================================================================
FILE: 07_category_intelligence.csv
==========================================================================================

Shape: (1087, 17)

Columns:
1. category
2. visitors
3. view_events
4. cart_events
5. transaction_events
6. unique_products
7. viewed_visitors
8. cart_visitors
9. transaction_visitors
10. view_to_cart_pct
11. cart_to_transaction_pct
12. view_to_transaction_pct
13. view_participation_pct
14. cart_participation_pct
15. transaction_participation_pct
16. categoryid
17. root_categoryid

Data Types:
category                          object
visitors                           int64
view_events                        int64
cart_events                        int64
transaction_events                 int64
unique_products                    int64
viewed_visitors                    int64
cart_visitors                    float64
transaction_visitors             float64
view_to_cart_pct                 float64
cart_to_transaction_pct          float64
view_to_transaction_pct          float64
view_participation_pct           float64
cart_participation_pct           float64
transaction_participation_pct    float64
categoryid                       float64
root_categoryid                  float64
dtype: object

First 3 Rows:

,category,visitors,view_events,cart_events,transaction_events,unique_products,viewed_visitors,cart_visitors,transaction_visitors,view_to_cart_pct,cart_to_transaction_pct,view_to_transaction_pct,view_participation_pct,cart_participation_pct,transaction_participation_pct,categoryid,root_categoryid
0,0,814,1049,59,12,95,803,44.0,12.0,5.479452,27.272727,1.494396,98.648649,5.405405,1.474201,0.0,1482.0
1,1,3757,5847,392,80,641,3747,197.0,55.0,5.257539,27.918782,1.467841,99.733830,5.243545,1.463934,1.0,1482.0
2,10,2,2,0,0,1,2,0.0,0.0,0.000000,NaN,0.000000,100.000000,0.000000,0.000000,10.0,755.0

==========================================================================================
FILE: 07_product_opportunities.csv
==========================================================================================

Shape: (122, 16)

Columns:
1. itemid
2. visitors
3. view_events
4. cart_events
5. transaction_events
6. viewed_visitors
7. cart_visitors
8. transaction_visitors
9. view_to_cart_pct
10. cart_to_transaction_pct
11. view_to_transaction_pct
12. categoryid
13. view_participation_pct
14. cart_participation_pct
15. transaction_participation_pct
16. opportunity_signal

Data Types:
itemid                             int64
visitors                           int64
view_events                        int64
cart_events                        int64
transaction_events                 int64
viewed_visitors                  float64
cart_visitors                    float64
transaction_visitors             float64
view_to_cart_pct                 float64
cart_to_transaction_pct          float64
view_to_transaction_pct          float64
categoryid                       float64
view_participation_pct           float64
cart_participation_pct           float64
transaction_participation_pct    float64
opportunity_signal                object
dtype: object

First 3 Rows:

,itemid,visitors,view_events,cart_events,transaction_events,viewed_visitors,cart_visitors,transaction_visitors,view_to_cart_pct,cart_to_transaction_pct,view_to_transaction_pct,categoryid,view_participation_pct,cart_participation_pct,transaction_participation_pct,opportunity_signal
0,187946,2912,3410,2,0,2911.0,2.0,0.0,0.068705,0.0,0.0,1393.0,99.965659,0.068681,0.0,High observed product interest with below-medi...
1,5411,2079,2325,9,0,2078.0,9.0,0.0,0.433109,0.0,0.0,789.0,99.951900,0.432900,0.0,High observed product interest with below-medi...
2,370653,1577,1854,0,0,1577.0,0.0,0.0,0.000000,NaN,0.0,82.0,100.000000,0.000000,0.0,High observed product interest with below-medi...

==========================================================================================
FILE: growth_opportunity_engine_output.csv
==========================================================================================

Shape: (10, 11)

Columns:
1. opportunity_rank
2. opportunity_type
3. entity_id
4. entity_label
5. affected_visitors
6. opportunity_score
7. priority
8. opportunity_class
9. decision
10. decision_urgency
11. recommended_action

Data Types:
opportunity_rank        int64
opportunity_type       object
entity_id              object
entity_label           object
affected_visitors     float64
opportunity_score     float64
priority               object
opportunity_class      object
decision               object
decision_urgency       object
recommended_action     object
dtype: object

First 3 Rows:

,opportunity_rank,opportunity_type,entity_id,entity_label,affected_visitors,opportunity_score,priority,opportunity_class,decision,decision_urgency,recommended_action
0,1,segment,Other Visitors,Other Visitors,1201156.0,100.000000,Critical,High-Reach Segment Friction,ACT NOW,Immediate,Prioritize targeted intervention for this high...
1,2,category,Uncategorized,Uncategorized,197747.0,91.191648,Critical,High-Reach Category Friction,ACT NOW,Immediate,Prioritize category-level conversion optimizat...
2,3,segment,At-Risk Visitors,At-Risk Visitors,113283.0,88.605031,Critical,High-Reach Segment Friction,ACT NOW,Immediate,Prioritize targeted intervention for this high...

In [4]:
assert len(verification_results) == 7, "Not all datasets were verified"

for file_name, details in verification_results.items():
    assert details["shape"][0] > 0, f"{file_name} is empty"
    assert len(details["columns"]) > 0, f"{file_name} has no columns"

print("=" * 70)
print("STREAMLIT DATA CONTRACT VALIDATION: PASSED")
print("Core datasets verified:", len(verification_results))
print("=" * 70)

======================================================================
STREAMLIT DATA CONTRACT VALIDATION: PASSED
Core datasets verified: 7
======================================================================